import type { ProductLocale, ProductToolId } from "./tool-catalog";

type LocalizedText = Record<ProductLocale, string>;

export type ToolGuide = {
  purpose: LocalizedText;
  input: LocalizedText;
  output: LocalizedText;
  processing: LocalizedText;
  privacy: LocalizedText;
  limitation: LocalizedText;
  example: LocalizedText;
  related: ProductToolId[];
  lastReviewed: string;
};

const local = (en: string, zh: string): LocalizedText => ({ en, zh });

export const toolGuides = {
  "website-check": {
    purpose: local("Find likely DNS, HTTP, TLS, CDN, and security-header problems from separate observation points.", "从不同观察点查找 DNS、HTTP、TLS、CDN 和安全响应头问题。"),
    input: local("A public domain or website URL, such as example.com.", "公开域名或网站地址，例如 example.com。"),
    output: local("A diagnostic report with evidence, likely causes, fixes, and verification steps.", "包含证据、可能原因、修复建议和验证步骤的诊断报告。"),
    processing: local("Your browser, a Cloudflare edge probe, and the OpsKitPro Probe on AWS Lightsail each provide distinct observations.", "你的浏览器、Cloudflare 边缘探针和 AWS Lightsail 上的 OpsKitPro 探针分别提供独立观察结果。"),
    privacy: local("The target is sent to OpsKitPro probes to perform the requested public-network checks. Results are not published as public reports.", "目标地址会发送给 OpsKitPro 探针以执行公开网络检测；结果不会作为公开报告发布。"),
    limitation: local("A blocked server probe does not prove a website is down. WAF rules, geography, and DNS propagation can make observation points disagree.", "服务端探针被拦截不代表网站宕机；WAF、地域和 DNS 传播可能让不同观察点结果不一致。"),
    example: local("Check example.com after a deployment to confirm the final HTTP status, certificate, DNS, and security headers.", "网站发布后检查 example.com，确认最终 HTTP 状态、证书、DNS 和安全响应头。"),
    related: ["network-doctor", "dns-security"],
    lastReviewed: "2026-08-06",
  },
  "network-doctor": {
    purpose: local("Explain the current connection's latency, IPv6, DNS response, reachability, and edge context.", "解释当前网络的延迟、IPv6、DNS 响应、服务可达性和边缘节点信息。"),
    input: local("Your current browser connection; optional public hosts are used only for bounded reachability checks.", "当前浏览器网络；可选公开主机仅用于有限的可达性检测。"),
    output: local("Connection-quality measurements and clearly labeled browser, edge, and server-probe evidence.", "网络质量测量，以及明确标注的浏览器、边缘节点和服务端探针证据。"),
    processing: local("Measurements combine browser APIs, Cloudflare request context, and bounded OpsKitPro Probe requests.", "测量结合浏览器 API、Cloudflare 请求上下文和有限的 OpsKitPro 探针请求。"),
    privacy: local("Basic network context reaches OpsKitPro when server-assisted checks run. The tool does not require an account or store a public history.", "运行服务端辅助检测时，基础网络信息会发送到 OpsKitPro；无需账号，也不会保存公开历史。"),
    limitation: local("Browser timing is not a bandwidth benchmark, and one probe location cannot represent every user's route.", "浏览器计时不等同于专业带宽测速，单个探针位置也不能代表所有用户线路。"),
    example: local("Use it when a video call is unstable to compare latency, IPv6, DNS, and service reachability clues.", "视频通话不稳定时，用它对比延迟、IPv6、DNS 和服务可达性线索。"),
    related: ["website-check", "cloudflare-trace"],
    lastReviewed: "2026-08-06",
  },
  "dns-security": {
    purpose: local("Inspect DNS records and evidence for SPF, DMARC, and CAA policies.", "检查 DNS 记录以及 SPF、DMARC、CAA 策略证据。"),
    input: local("A public domain and, where supported, a DNS record type.", "公开域名，以及支持情况下的 DNS 记录类型。"),
    output: local("Resolved records plus evidence-led email and certificate-policy checks.", "解析到的记录，以及基于证据的邮件与证书策略检查。"),
    processing: local("Queries run through the OpsKitPro server-side DNS resolver.", "查询通过 OpsKitPro 服务端 DNS 解析器执行。"),
    privacy: local("The requested public domain is sent to OpsKitPro. No account is required and no private DNS zone is accessed.", "所查询的公开域名会发送到 OpsKitPro；无需账号，也不会访问私有 DNS 区域。"),
    limitation: local("A record's presence does not prove that mail delivery or anti-spoofing is configured correctly end to end.", "记录存在不代表邮件投递或反伪造配置在全链路上一定正确。"),
    example: local("Look up example.com to verify its A, MX, TXT, SPF, DMARC, and CAA evidence before changing DNS.", "修改 DNS 前查询 example.com，核对 A、MX、TXT、SPF、DMARC 和 CAA 证据。"),
    related: ["website-check", "api"],
    lastReviewed: "2026-08-06",
  },
  "ip-lookup": {
    purpose: local("Identify public IP ownership, ASN, provider, and approximate location hints.", "查询公网 IP 的归属、ASN、网络提供商和大致位置线索。"),
    input: local("A public IPv4 or IPv6 address, or your current public address.", "公网 IPv4、IPv6 地址，或当前公网地址。"),
    output: local("Country-level location, continent, ASN, network organization, and organization domain.", "国家级位置、洲、ASN、网络组织及组织域名。"),
    processing: local("Specified IPs are queried against a read-only IPinfo Lite database stored locally on the OpsKitPro server; current-visitor context may also use Cloudflare request metadata.", "指定 IP 通过 OpsKitPro 服务器本地只读的 IPinfo Lite 数据库查询；当前访客信息也可能使用 Cloudflare 请求元数据。"),
    privacy: local("The queried address reaches OpsKitPro but is not forwarded to an external lookup API. IP country data is approximate and should not be used to identify a person.", "所查询地址会到达 OpsKitPro，但不会再转发给外部 IP 查询 API；IP 国家数据是近似结果，不应用于识别个人。"),
    limitation: local("IPinfo Lite does not provide city, coordinates, timezone, hosting type, or VPN/proxy detection. Those fields remain explicitly unknown.", "IPinfo Lite 不提供城市、坐标、时区、托管类型或 VPN/代理检测；这些字段会明确保持未知。"),
    example: local("Check 8.8.8.8 to see its ASN and provider rather than assuming the user's physical location.", "查询 8.8.8.8 的 ASN 和提供商，不要把结果当作用户的精确物理位置。"),
    related: ["network-doctor", "cloudflare-trace"],
    lastReviewed: "2026-08-10",
  },
  "cloudflare-trace": {
    purpose: local("Explain how a request reaches Cloudflare, including colo, protocol, TLS, WARP, and Gateway context.", "解释请求如何到达 Cloudflare，包括机房、协议、TLS、WARP 和 Gateway 信息。"),
    input: local("Your current connection or a supported public target domain.", "当前网络连接，或受支持的公开目标域名。"),
    output: local("Parsed Cloudflare trace fields with plain-language labels.", "带有通俗说明的 Cloudflare Trace 字段。"),
    processing: local("Your own trace is observed at the Cloudflare edge; target checks may use an OpsKitPro server request.", "自身 Trace 在 Cloudflare 边缘观察；目标检测可能使用 OpsKitPro 服务端请求。"),
    privacy: local("Cloudflare and OpsKitPro receive normal request metadata. The result is not a proof of identity or exact location.", "Cloudflare 和 OpsKitPro 会接收常规请求信息；结果不能证明身份或精确位置。"),
    limitation: local("Trace fields describe one request path and can change between networks, devices, or moments.", "Trace 字段只描述一次请求路径，可能随网络、设备和时间变化。"),
    example: local("Compare the colo and protocol on home broadband and mobile data when only one network feels slow.", "只有一种网络较慢时，对比家庭宽带与移动网络的机房和协议字段。"),
    related: ["network-doctor", "ip-lookup"],
    lastReviewed: "2026-08-06",
  },
  api: {
    purpose: local("Run bounded DNS, IP, HTTP, and full diagnostic checks from scripts or agents.", "通过脚本或智能体调用有安全边界的 DNS、IP、HTTP 和完整诊断。"),
    input: local("Validated query parameters such as a public domain, IP address, or HTTP(S) URL.", "经过校验的查询参数，例如公开域名、IP 地址或 HTTP(S) 地址。"),
    output: local("Versioned JSON envelopes with result or error details and request metadata.", "带结果或错误详情及请求元数据的版本化 JSON 响应。"),
    processing: local("Requests run on OpsKitPro servers with SSRF, redirect, timeout, size, and rate-limit boundaries.", "请求在 OpsKitPro 服务端执行，并受 SSRF、跳转、超时、大小和频率限制保护。"),
    privacy: local("Inputs and normal server logs reach OpsKitPro. Do not send secrets, private hosts, tokens, or personal data.", "输入和常规服务日志会到达 OpsKitPro；请勿发送密钥、私有主机、令牌或个人数据。"),
    limitation: local("The public v0 API is rate-limited, unauthenticated, and unsuitable for private-network monitoring or guaranteed uptime SLAs.", "公开 v0 API 有频率限制且无需认证，不适合私网监控或可用性 SLA。"),
    example: local("Call the HTTP endpoint from CI to confirm a public release URL returns the expected final status.", "在 CI 中调用 HTTP 接口，确认公开发布地址返回预期最终状态。"),
    related: ["website-check", "dns-security"],
    lastReviewed: "2026-08-06",
  },
  json: {
    purpose: local("Format, minify, repair, and convert JSON in a focused local workspace.", "在专注的本地工作区中格式化、压缩、修复和转换 JSON。"),
    input: local("JSON text, including malformed JSON that may be repairable.", "JSON 文本，也可以是可能修复的格式错误 JSON。"),
    output: local("Formatted, minified, or repaired JSON, plus JSON-to-YAML/TOML conversions.", "格式化、压缩或修复后的 JSON，以及 JSON 到 YAML/TOML 的转换结果。"),
    processing: local("Processing runs in your browser.", "处理在你的浏览器本地完成。"),
    privacy: local("Pasted JSON is not sent to OpsKitPro by the tool. Browser extensions and the device environment remain outside our control.", "工具不会把粘贴的 JSON 发送到 OpsKitPro；浏览器扩展和设备环境不在本站控制范围内。"),
    limitation: local("Automatic repair is heuristic. Review the result before using it in production or signing data.", "自动修复基于规则推断；用于生产或数据签名前请人工核对。"),
    example: local("Paste a malformed API response, repair trailing commas, then copy the formatted JSON.", "粘贴格式错误的 API 响应，修复多余逗号，再复制格式化结果。"),
    related: ["api", "encode"],
    lastReviewed: "2026-08-06",
  },
  websocket: {
    purpose: local("Open and inspect WebSocket sessions, messages, templates, and ping behavior.", "建立并检查 WebSocket 会话、消息、模板和 Ping 行为。"),
    input: local("A ws:// or wss:// endpoint plus optional headers/subprotocols and message payloads.", "ws:// 或 wss:// 地址，以及可选的协议配置和消息内容。"),
    output: local("Connection state, timestamped incoming/outgoing messages, and ping observations.", "连接状态、带时间戳的收发消息和 Ping 观察结果。"),
    processing: local("The connection is opened directly by your browser to the endpoint you provide.", "连接由你的浏览器直接建立到所填写的目标地址。"),
    privacy: local("OpsKitPro does not relay message content, but the destination server receives everything you send.", "OpsKitPro 不转发消息内容，但目标服务器会收到你发送的所有数据。"),
    limitation: local("Browser security rules can block custom headers, insecure ws:// from HTTPS pages, or endpoints with certificate problems.", "浏览器安全规则可能阻止自定义请求头、HTTPS 页面中的 ws:// 或证书异常的服务。"),
    example: local("Connect to a test echo endpoint, send a JSON message, and inspect the returned frame and latency.", "连接测试 Echo 服务，发送 JSON 消息并检查返回帧和延迟。"),
    related: ["json", "api"],
    lastReviewed: "2026-08-06",
  },
  passgen: {
    purpose: local("Generate strong, customizable passwords without uploading them.", "生成可自定义的高强度密码，不上传密码内容。"),
    input: local("Length and character-set preferences such as uppercase, numbers, and symbols.", "长度及字符集偏好，例如大写字母、数字和符号。"),
    output: local("A generated password and an estimated strength indication.", "生成的密码及强度估计。"),
    processing: local("Generation runs in your browser using the device's cryptographic random source.", "使用设备的加密随机源在浏览器本地生成。"),
    privacy: local("Generated passwords are not sent to OpsKitPro. Clipboard managers and browser extensions may still observe copied text.", "生成的密码不会发送到 OpsKitPro；剪贴板管理器和浏览器扩展仍可能读取复制内容。"),
    limitation: local("A strong password still needs unique use and secure storage in a trusted password manager.", "高强度密码仍需避免复用，并保存在可信的密码管理器中。"),
    example: local("Generate a 20-character password with mixed case, numbers, and symbols for a new account.", "为新账号生成 20 位、包含大小写字母、数字和符号的密码。"),
    related: ["qrgen", "encode"],
    lastReviewed: "2026-08-06",
  },
  qrgen: {
    purpose: local("Turn links or short text into a downloadable QR code.", "把链接或短文本转换成可下载的二维码。"),
    input: local("A URL or short text plus size and appearance options.", "链接或短文本，以及尺寸和外观选项。"),
    output: local("A scannable QR preview and downloadable image.", "可扫码预览及可下载的二维码图片。"),
    processing: local("QR encoding and image generation run in your browser.", "二维码编码和图片生成在浏览器本地完成。"),
    privacy: local("Entered content is not sent to OpsKitPro by the generator. Anyone who scans the QR can read or open its content.", "生成器不会把输入内容发送到 OpsKitPro；任何扫码者都能读取或打开其中内容。"),
    limitation: local("Dense content, low contrast, small print, or a damaged image can reduce scan reliability. Test before distribution.", "内容过长、对比度低、印刷过小或图片损坏都会降低识别率，发布前请实测。"),
    example: local("Create a QR code for a store page, download it, and test it on two phones before printing.", "为店铺页面生成二维码，下载后先用两台手机测试再印刷。"),
    related: ["passgen", "encode"],
    lastReviewed: "2026-08-06",
  },
  encode: {
    purpose: local("Encode or decode URL components, Base64, HTML entities, and common text representations.", "编码或解码 URL、Base64、HTML 实体和常用文本表示。"),
    input: local("Text plus the selected encoding or decoding operation.", "文本及所选择的编码或解码方式。"),
    output: local("The converted text, ready to copy.", "转换后的可复制文本。"),
    processing: local("Conversion runs in your browser.", "转换在你的浏览器本地完成。"),
    privacy: local("Entered text is not sent to OpsKitPro by the tool. Do not mistake encoding for encryption.", "工具不会把输入文本发送到 OpsKitPro；编码不等于加密。"),
    limitation: local("The correct character encoding matters, and decoded content may be unsafe to execute or render as HTML.", "字符编码选择会影响结果；解码后的内容也可能不适合直接执行或渲染为 HTML。"),
    example: local("Decode a Base64 API value or safely encode a Chinese search term for a URL query parameter.", "解码 Base64 API 字段，或把中文搜索词安全编码为 URL 查询参数。"),
    related: ["json", "qrgen"],
    lastReviewed: "2026-08-06",
  },
  time: {
    purpose: local("Convert Unix timestamps and compare times across zones.", "转换 Unix 时间戳并比较不同时区时间。"),
    input: local("A timestamp, date/time, or timezone selection.", "时间戳、日期时间或时区选择。"),
    output: local("Human-readable local/UTC times and equivalent timestamps.", "易读的本地/UTC 时间及对应时间戳。"),
    processing: local("Conversion runs in your browser using its timezone database.", "使用浏览器时区数据库在本地完成转换。"),
    privacy: local("Entered dates and timestamps are not sent to OpsKitPro by the tool.", "输入的日期和时间戳不会发送到 OpsKitPro。"),
    limitation: local("Timezone rules and daylight-saving history vary; verify legally or financially sensitive deadlines with an authoritative source.", "时区和夏令时历史规则会变化；涉及法律或财务的重要期限请用权威来源复核。"),
    example: local("Convert 1775638800 into Beijing time and UTC when investigating a server log.", "排查服务器日志时，把 1775638800 转换成北京时间和 UTC。"),
    related: ["encode", "json"],
    lastReviewed: "2026-08-06",
  },
  regex: {
    purpose: local("Test JavaScript regular expressions and inspect matches without uploading the pattern or text.", "测试 JavaScript 正则表达式并检查匹配结果，不上传表达式或文本。"),
    input: local("A JavaScript regular expression without surrounding slashes, flags, and test text.", "不带两侧斜杠的 JavaScript 正则表达式、标志和测试文本。"),
    output: local("Highlighted matches, JavaScript start/end indices, capture groups, and a copyable summary.", "匹配高亮、JavaScript 起止索引、捕获组和可复制摘要。"),
    processing: local("The expression runs in an isolated Web Worker in your browser with time and result limits.", "表达式在浏览器隔离的 Web Worker 中运行，并受超时与结果数量限制。"),
    privacy: local("Patterns, test text, matches, and capture groups are not sent to OpsKitPro or saved by the tool.", "表达式、测试文本、匹配内容和捕获组不会发送给 OpsKitPro，也不会由工具保存。"),
    limitation: local("This tool uses JavaScript RegExp syntax, not PCRE. A timeout limits browser impact but does not prove an expression is safe from ReDoS in another system.", "本工具使用 JavaScript RegExp 语法而非 PCRE；超时只能限制浏览器影响，不能证明表达式在其他系统中不存在 ReDoS 风险。"),
    example: local("Test an email pattern against a log sample and inspect named user and domain groups.", "用日志样例测试邮箱表达式，并检查命名的用户与域名捕获组。"),
    related: ["encode", "json"],
    lastReviewed: "2026-08-19",
  },
  jwt: {
    purpose: local("Decode JWT header/payload, inspect claims, and verify signatures in-browser without upload.", "在本地解码 JWT header/payload，检查声明并进行本地签名校验，不上传数据。"),
    input: local("JWT token text, and optional HMAC secret for HS256/HS384/HS512.", "JWT 文本，以及可选的 HS256/HS384/HS512 HMAC 密钥。"),
    output: local("Parsed token parts, claims, risk checks, and verification status.", "解析后的 token 分段、声明、风险检查和签名校验状态。"),
    processing: local("The token is parsed with native browser APIs. Signature verification uses Web Crypto only in the current tab.", "在浏览器当前标签页本地解析，签名验证通过 Web Crypto 在本地执行。"),
    privacy: local("Token, payload, and secret are processed in your browser. No network request is required.", "Token、负载与密钥都在本地处理，无需网络请求。"),
    limitation: local("Only HS256/HS384/HS512 are supported in this MVP. RS256/JWS certificate verification is recommended to add in a later phase.", "当前 MVP 仅支持 HS256/HS384/HS512。RS256/JWS 证书链校验建议后续扩展。"),
    example: local("Paste an app JWT and verify it against the shared HMAC secret, then inspect exp and issuer claims.", "粘贴应用 JWT 并用共享密钥校验签名，再检查 exp 与 iss 声明。"),
    related: ["regex", "hash"],
    lastReviewed: "2026-08-19",
  },
  uuid: {
    purpose: local("Generate UUIDs locally and validate UUID formatting for common versions.", "在本地生成 UUID 并校验常见版本的格式。"),
    input: local("Generate mode and optional v5 namespace/name, or paste a UUID to validate.", "选择生成模式并可选输入 v5 的命名空间与名称，或粘贴 UUID 进行校验。"),
    output: local("Generated UUIDs and validation result including version and format status.", "生成的 UUID 及校验结果（含版本和格式状态）。"),
    processing: local("All generation and validation happen in your browser, never sent over the network.", "所有生成与校验均在浏览器本地完成，不经过网络。"),
    privacy: local("No UUID value or namespace input is uploaded by this tool.", "工具不上传 UUID 或命名空间输入到服务器。"),
    limitation: local("v1, v4, and v5 generation are supported. v3 generation is not included; v5 requires a valid namespace and input name.", "支持生成 v1、v4 和 v5；当前不生成 v3，v5 需要有效命名空间与名称。"),
    example: local("Generate a v4 UUID for request IDs, then validate a pasted token before use.", "为请求 ID 生成 v4 UUID，之后再校验粘贴的 UUID 是否符合预期版本。"),
    related: ["hash", "jwt"],
    lastReviewed: "2026-08-19",
  },
  "sensitive-data": {
    purpose: local("Detect common sensitive entities in pasted text and produce redacted output without uploads.", "检测粘贴文本中的常见敏感实体并一键生成脱敏文本，不上传数据。"),
    input: local("Raw text that may contain emails, phone numbers, API keys/tokens, UUIDs, private keys, or card-like identifiers.", "可能包含邮箱、手机号、API Key / Token、UUID、私钥片段或卡号的原始文本。"),
    output: local("Sensitivity summary, highlighted matches, and redacted text with stable placeholders.", "脱敏摘要、匹配高亮以及带稳定占位符的脱敏文本。"),
    processing: local("All scanning and replacement logic runs entirely in your browser.", "检测与替换逻辑全部在浏览器本地执行。"),
    privacy: local("No text is sent to OpsKitPro. Clipboard and browser extensions are not controlled by this tool.", "该工具不会向 OpsKitPro 发送文本；剪贴板与浏览器扩展不在本工具控制范围内。"),
    limitation: local("Regex-based matching is pragmatic and may miss unusual formats or long obfuscated patterns.", "规则匹配为实用方案，可能漏检非常规或经过混淆的格式。"),
    example: local("Paste logs before sharing: detect secrets first, then copy redacted output to tickets or chats.", "在分享日志前先检测，再复制脱敏后的文本用于工单或聊天。"),
    related: ["hash", "regex"],
    lastReviewed: "2026-08-19",
  },
  cron: {
    purpose: local(
      "Build standard 5-field cron expressions and get readable schedule interpretation locally.",
      "在浏览器本地构建标准 5 字段 cron 表达式，并获取可读的执行规则说明。",
    ),
    input: local(
      "A quick preset or custom five-field expression with minute hour day-of-month month day-of-week.",
      "快捷模板或自定义五段表达式（分钟、小时、日、月、周），例如 0 2 * * 1。",
    ),
    output: local(
      "A valid cron expression and a plain-language schedule breakdown with quick generation hints.",
      "生成有效 cron 表达式和可读的执行计划说明，并给出快速生成建议。",
    ),
    processing: local(
      "Everything runs in your browser only. The tool does not validate targets or trigger any background jobs.",
      "全部逻辑在浏览器内运行。工具不验证目标主机，不触发任何后台任务。",
    ),
    privacy: local(
      "Your schedule expressions are not uploaded. Copying results still depends on your browser clipboard privacy context.",
      "表达式不会上传。复制结果仍受你当前浏览器剪贴板权限和环境控制。",
    ),
    limitation: local(
      "Only standard 5-field UNIX-like cron syntax is supported. Quartz extensions and 6-7 field variants are not covered yet.",
      "当前仅支持标准 5 段 UNIX 风格 cron，不支持 Quartz 的 6/7 段扩展语法。",
    ),
    example: local(
      "Generate a weekly task at 02:30 on Monday and export the cron plus explanation for your ops runbook.",
      "生成周一 02:30 的执行表达式，并导出 cron 与解释用于运维手册。",
    ),
    related: ["time", "regex"],
    lastReviewed: "2026-08-19",
  },
  yaml: {
    purpose: local("Validate and format YAML text locally, and return readable parse errors.", "在本地校验并格式化 YAML 文本，返回可读的解析错误。"),
    input: local("YAML text content pasted into the editor.", "粘贴到编辑器中的 YAML 文本内容。"),
    output: local("Formatted YAML and parse-success/failure feedback with position hints.", "格式化后的 YAML，以及带位置信息的解析成功/失败反馈。"),
    processing: local("All parsing and formatting runs in your browser only. No API call is made.", "所有解析和格式化都在浏览器本地运行，不会调用任何 API。"),
    privacy: local("The pasted YAML never leaves your browser for this tool.", "该工具不会将粘贴的 YAML 发送到服务器。"),
    limitation: local("Line and column pointers depend on parser behavior. Duplicate keys are rejected by the parser in this MVP.", "行列定位依赖解析器实现；当前 MVP 会将重复键视为非法。"),
    example: local("Format a multi-line deployment config and copy the corrected YAML back to your pipeline.", "格式化一段多行部署配置，并复制修正后的 YAML 回流到你的流水线。"),
    related: ["json", "encode"],
    lastReviewed: "2026-08-19",
  },
  sql: {
    purpose: local("Format SQL text locally to improve readability and reduce review noise before sharing or committing.", "在本地格式化 SQL 文本，提升可读性并降低评审时的噪音。"),
    input: local("Raw SQL text copied from applications, scripts, or query logs.", "从应用、脚本或日志中复制的 SQL 文本。"),
    output: local("A browser-local, whitespace-normalized SQL output with grouped clauses and indentation.", "在浏览器本地输出经过空白归一化的 SQL，包含按分句分组和缩进。"),
    processing: local("Formatting runs in your browser. No SQL is sent to OpsKitPro.", "格式化在浏览器内进行，不会将 SQL 发送到 OpsKitPro。"),
    privacy: local("The pasted SQL stays in the current browser and can be copied manually.", "粘贴的 SQL 保留在当前浏览器，可手动复制结果。"),
    limitation: local("This formatter is intentionally lightweight and may not honor every SQL dialect edge case or comment style perfectly.", "该格式化器为轻量版本，可能不完全支持所有 SQL 方言边缘语法或注释风格。"),
    example: local("Format a raw SELECT/INSERT/UPDATE snippet before pasting into review notes or ticket comments.", "在粘贴到评审或工单前先格式化 SELECT/INSERT/UPDATE 片段。"),
    related: ["yaml", "json"],
    lastReviewed: "2026-08-19",
  },
  color: {
    purpose: local("Convert color values between common formats and preview them locally.", "在本地完成常见颜色格式之间的转换并进行预览。"),
    input: local("Hex, RGB, RGBA, or HSL style color text, or a selected color.", "Hex、RGB、RGBA 或 HSL 颜色文本，或直接通过取色器选择。"),
    output: local("Normalized Hex, RGB(A), and HSL values with quick copy actions.", "标准化后的 Hex、RGB(A)、HSL 值，并可一键复制。"),
    processing: local("All conversions happen in your browser and do not send any value to a server.", "全部转换在浏览器内完成，不会向服务器上传颜色值。"),
    privacy: local("Colors are processed in the current tab only. Copy output manually when needed.", "颜色值仅在当前标签页处理，必要时手动复制结果。"),
    limitation: local("Very old or malformed color notation is intentionally rejected in this MVP.", "老旧或格式异常的颜色表示在当前 MVP 中会被拒绝。"),
    example: local("Convert a design export color quickly before pasting it into CSS or SQL/JSON payloads.", "将设计导出的颜色快速转换后再粘贴到 CSS 或 JSON 载荷中。"),
    related: ["qrgen", "encode"],
    lastReviewed: "2026-08-19",
  },
  hash: {
    purpose: local("Generate and compare checksums for text or one local file without uploading the input.", "为文本或单个本地文件生成并比对校验值，不上传输入内容。"),
    input: local("UTF-8 text or one local file, an algorithm, and an optional expected checksum.", "UTF-8 文本或单个本地文件、算法，以及可选的预期校验值。"),
    output: local("A lowercase hexadecimal MD5, SHA-1, SHA-256, SHA-384, or SHA-512 digest and comparison status.", "小写十六进制 MD5、SHA-1、SHA-256、SHA-384 或 SHA-512 摘要及比对状态。"),
    processing: local("Text uses browser cryptography where available; files are read in chunks inside an isolated Web Worker.", "文本尽可能使用浏览器密码学能力；文件在隔离的 Web Worker 中分块读取。"),
    privacy: local("Text, file names, file bytes, generated digests, and expected values are not sent to OpsKitPro or saved by the tool.", "文本、文件名、文件字节、生成摘要和预期值不会发送给 OpsKitPro，也不会由工具保存。"),
    limitation: local("A matching checksum confirms identical bytes, not origin or trust. MD5 and SHA-1 are compatibility-only and unsafe for security decisions.", "校验值一致只能证明字节相同，不能证明来源可信；MD5 和 SHA-1 仅用于兼容，不能用于安全判断。"),
    example: local("Compare a downloaded release file's SHA-256 with the checksum published by its vendor.", "将下载的发布文件 SHA-256 与供应商公布的校验值进行比对。"),
    related: ["passgen", "regex"],
    lastReviewed: "2026-08-19",
  },
  "prompt-builder": {
    purpose: local("Turn a rough request into a reusable prompt with context, constraints, and output rules.", "把模糊需求整理成包含上下文、约束和输出规则的可复用提示词。"),
    input: local("Your task, background, constraints, examples, and desired output format.", "任务、背景、限制条件、示例和期望输出格式。"),
    output: local("A structured prompt you can copy into the AI service of your choice.", "可复制到所选 AI 服务中的结构化提示词。"),
    processing: local("Prompt assembly runs in your browser and does not call an AI model.", "提示词整理在浏览器本地完成，不调用 AI 模型。"),
    privacy: local("Entered content is not sent to OpsKitPro by the builder. The AI service you later use has its own data policy.", "构建器不会把输入内容发送到 OpsKitPro；之后使用的 AI 服务有其独立数据政策。"),
    limitation: local("Structure can improve clarity but cannot guarantee factual, safe, or consistent model output.", "清晰结构有助于表达，但不能保证模型输出事实正确、安全或稳定。"),
    example: local("Build a prompt that asks an AI to rewrite a customer notice in plain Chinese with a 120-character limit.", "构建提示词，让 AI 用通俗中文改写客户通知，并限制在 120 字内。"),
    related: ["json", "time"],
    lastReviewed: "2026-08-06",
  },
} satisfies Record<ProductToolId, ToolGuide>;

export function localizeToolGuide(id: ProductToolId, lang: ProductLocale) {
  const guide = toolGuides[id];
  return {
    purpose: guide.purpose[lang],
    input: guide.input[lang],
    output: guide.output[lang],
    processing: guide.processing[lang],
    privacy: guide.privacy[lang],
    limitation: guide.limitation[lang],
    example: guide.example[lang],
    related: guide.related,
    lastReviewed: guide.lastReviewed,
  };
}
