import Link from 'next/link'
import { ArrowLeft, BarChart3, Cloud, ExternalLink, Laptop } from 'lucide-react'

export default function AdminAnalyticsPage() {
  return (
    <main className="mx-auto w-full max-w-5xl flex-grow px-4 pb-20 pt-8 sm:px-6">
      <Link href="/admin" className="inline-flex items-center gap-2 text-sm font-semibold text-[var(--text-muted)] hover:text-[var(--accent-color)]">
        <ArrowLeft className="h-4 w-4" />
        Admin
      </Link>

      <div className="mt-6">
        <div className="flex items-center gap-2 text-xs font-semibold uppercase text-[var(--accent-color)]">
          <BarChart3 className="h-4 w-4" />
          Analytics
        </div>
        <h1 className="mt-3 text-3xl font-semibold text-[var(--text-primary)]">Traffic and operations</h1>
        <p className="mt-3 max-w-2xl text-sm leading-6 text-[var(--text-muted)]">
          Analytics data and generated reports stay in the private operations repository. Use the links below to inspect the current sources.
        </p>
      </div>

      <section className="mt-8 grid gap-4 md:grid-cols-2">
        <a href="https://dash.cloudflare.com" target="_blank" rel="noreferrer" className="group rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-primary)] p-5 shadow-[var(--shadow-soft)] hover:border-emerald-500/25">
          <Cloud className="h-6 w-6 text-[var(--accent-color)]" />
          <h2 className="mt-5 flex items-center gap-2 text-lg font-semibold text-[var(--text-primary)]">
            Cloudflare Analytics
            <ExternalLink className="h-4 w-4 text-[var(--text-faint)]" />
          </h2>
          <p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Review live traffic, security events, and Worker activity.</p>
        </a>
        <a href="http://127.0.0.1:4173" target="_blank" rel="noreferrer" className="group rounded-xl border border-[var(--border-subtle)] bg-[var(--surface-primary)] p-5 shadow-[var(--shadow-soft)] hover:border-emerald-500/25">
          <Laptop className="h-6 w-6 text-[var(--accent-color)]" />
          <h2 className="mt-5 flex items-center gap-2 text-lg font-semibold text-[var(--text-primary)]">
            Private ops dashboard
            <ExternalLink className="h-4 w-4 text-[var(--text-faint)]" />
          </h2>
          <p className="mt-2 text-sm leading-6 text-[var(--text-muted)]">Open the local read-only dashboard generated by `opskitpro-ops`.</p>
        </a>
      </section>
    </main>
  )
}
