import React, { useState } from 'react'
import { ShieldCheck, ShieldAlert, Shield, AlertCircle, Info, Mail, Lock, Server, Download, Check } from 'lucide-react'
import type { SecurityAuditResult, AuditStatus } from '../hooks'

export function SecurityAuditPanel({ 
  result, 
  lang 
}: { 
  result: SecurityAuditResult
  lang: 'zh' | 'en' | 'ja' | 'tw' 
}) {
  const isJapanese = lang === 'ja'
  const isZh = lang === 'zh'
  const isTw = lang === 'tw'

  const t = {
    scoreTitle: isJapanese ? 'ドメインセキュリティスコア' : isZh ? '域名安全评分' : isTw ? '網域名稱安全評分' : 'Domain Security Score',
    spfTitle: 'SPF',
    spfDesc: isJapanese ? '送信元認証' : isZh ? '发件人身份验证' : isTw ? '寄件者身分驗證' : 'Sender Policy Framework',
    dmarcTitle: 'DMARC',
    dmarcDesc: isJapanese ? 'メール認証・レポート' : isZh ? '邮件认证与报告' : isTw ? '郵件認證與報告' : 'Domain-based Message Authentication',
    caaTitle: 'CAA',
    caaDesc: isJapanese ? '証明書発行の制限' : isZh ? '证书颁发机构授权' : isTw ? '憑證發行機構授權' : 'Certificate Authority Authorization',
  }

  const getStatusColor = (status: AuditStatus) => {
    switch (status) {
      case 'pass': return 'text-emerald-600 bg-emerald-50 border-emerald-200'
      case 'warning': return 'text-amber-600 bg-amber-50 border-amber-200'
      case 'fail': return 'text-red-600 bg-red-50 border-red-200'
      case 'info': return 'text-sky-600 bg-sky-50 border-sky-200'
    }
  }

  const getStatusIcon = (status: AuditStatus) => {
    switch (status) {
      case 'pass': return <ShieldCheck className="w-5 h-5" />
      case 'warning': return <ShieldAlert className="w-5 h-5" />
      case 'fail': return <AlertCircle className="w-5 h-5" />
      case 'info': return <Info className="w-5 h-5" />
    }
  }

  const [exporting, setExporting] = useState(false)

  const handleExport = () => {
    setExporting(true)
    try {
      const payload = JSON.stringify({ event: 'dns_audit_export', page: window.location.pathname, target: result.domain })
      if (navigator.sendBeacon) navigator.sendBeacon('/api/event', new Blob([payload], { type: 'application/json' }))
      else fetch('/api/event', { method: 'POST', body: payload, keepalive: true }).catch(() => null)
    } catch {}

    const dateStr = new Date().toISOString().split('T')[0]
    const mdContent = `# Domain Security Audit Report
**Domain:** \`${result.domain}\`
**Date:** ${dateStr}
**Overall Security Score:** ${result.score}

---

## 1. Sender Policy Framework (SPF)
**Status:** ${result.spf.status.toUpperCase()}

${result.spf.message}

**Records:**
${result.spf.records.length > 0 ? result.spf.records.map(r => `- \`${r}\``).join('\n') : '*No SPF records found.*'}

## 2. Domain-based Message Authentication, Reporting, and Conformance (DMARC)
**Status:** ${result.dmarc.status.toUpperCase()}

${result.dmarc.message}

**Records:**
${result.dmarc.record ? `- \`${result.dmarc.record}\`` : '*No DMARC records found.*'}

## 3. Certificate Authority Authorization (CAA)
**Status:** ${result.caa.status.toUpperCase()}

${result.caa.message}

**Records:**
${result.caa.records.length > 0 ? result.caa.records.map(r => `- \`${r}\``).join('\n') : '*No CAA records found.*'}

---

## Risk Summary & Recommended Actions
- **SPF**: ${result.spf.status === 'pass' ? 'Your SPF is strictly configured.' : result.spf.status === 'warning' ? 'Consider upgrading to a strict \`-all\` policy once you map out all legitimate senders.' : 'You must configure a valid SPF record to prevent spoofing.'}
- **DMARC**: ${result.dmarc.status === 'pass' ? 'Your DMARC is securely set to reject.' : result.dmarc.status === 'warning' || result.dmarc.status === 'info' ? 'Monitor your DMARC reports (\`rua\`) and progressively upgrade to \`p=reject\`.' : 'You must configure a DMARC record to protect your domain.'}
- **CAA**: ${result.caa.status === 'pass' ? 'CAA is active.' : 'Consider adding CAA records to limit which Certificate Authorities can issue certificates for your domain.'}

*Generated by OpsKitPro Diagnostics Hub*
`
    const blob = new Blob([mdContent], { type: 'text/markdown;charset=utf-8' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `security_audit_${result.domain}_${dateStr}.md`
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    
    setTimeout(() => setExporting(false), 2000)
  }

  return (
    <div className="space-y-6">
      {/* Score Header */}
      <div className="bg-white rounded-[2rem] p-8 border border-zinc-100 shadow-sm flex items-center justify-between gap-6 relative overflow-hidden">
        <div className="absolute top-0 right-0 w-64 h-64 bg-zinc-50 rounded-full blur-3xl pointer-events-none -mr-32 -mt-32"></div>
        <div className="relative z-10 flex items-center gap-6">
          <div className={`w-20 h-20 rounded-2xl flex items-center justify-center text-4xl font-black ${
            result.score === 'A' ? 'bg-emerald-100 text-emerald-600' :
            result.score === 'B' ? 'bg-amber-100 text-amber-600' :
            result.score === 'C' ? 'bg-orange-100 text-orange-600' :
            'bg-red-100 text-red-600'
          }`}>
            {result.score}
          </div>
          <div>
            <h3 className="text-sm font-bold text-zinc-400 uppercase tracking-widest mb-1">{t.scoreTitle}</h3>
            <p className="text-2xl font-semibold text-zinc-900">{result.domain}</p>
          </div>
        </div>
        
        <button 
          onClick={handleExport}
          className="relative z-10 shrink-0 inline-flex items-center gap-2 rounded-xl bg-zinc-900 hover:bg-zinc-800 text-white px-5 py-3 text-xs font-bold transition-colors shadow-md"
        >
          {exporting ? <Check className="w-4 h-4 text-emerald-400" /> : <Download className="w-4 h-4" />}
          {exporting ? (isJapanese ? 'エクスポート完了' : isZh ? '已导出' : isTw ? '已匯出' : 'Exported') : (isJapanese ? 'レポート出力' : isZh ? '导出 Markdown' : isTw ? '匯出 Markdown' : 'Export Report')}
        </button>
      </div>

      {/* Cards Grid */}
      <div className="grid md:grid-cols-3 gap-6">
        
        {/* SPF */}
        <div className={`bg-white rounded-[2rem] p-6 border shadow-sm relative overflow-hidden transition-all hover:shadow-md ${getStatusColor(result.spf.status).replace('bg-', 'hover:bg-').replace('border-', 'hover:border-')}`}>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-xl ${getStatusColor(result.spf.status)}`}>
                <Mail className="w-5 h-5" />
              </div>
              <div>
                <h4 className="font-bold text-zinc-900">{t.spfTitle}</h4>
                <p className="text-xs text-zinc-500">{t.spfDesc}</p>
              </div>
            </div>
            <div className={getStatusColor(result.spf.status).split(' ')[0]}>
              {getStatusIcon(result.spf.status)}
            </div>
          </div>
          <div className="bg-zinc-50 p-3 rounded-xl mb-4 min-h-16 flex items-center">
            <p className="text-sm font-medium text-zinc-700">{result.spf.message}</p>
          </div>
          <div className="space-y-2">
            {result.spf.records.map((r, i) => (
              <div key={i} className="text-xs font-mono text-zinc-500 bg-zinc-100/50 p-2 rounded truncate" title={r}>{r}</div>
            ))}
            {result.spf.records.length === 0 && <div className="text-xs text-zinc-400 italic">No record</div>}
          </div>
        </div>

        {/* DMARC */}
        <div className={`bg-white rounded-[2rem] p-6 border shadow-sm relative overflow-hidden transition-all hover:shadow-md ${getStatusColor(result.dmarc.status).replace('bg-', 'hover:bg-').replace('border-', 'hover:border-')}`}>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-xl ${getStatusColor(result.dmarc.status)}`}>
                <Shield className="w-5 h-5" />
              </div>
              <div>
                <h4 className="font-bold text-zinc-900">{t.dmarcTitle}</h4>
                <p className="text-xs text-zinc-500">{t.dmarcDesc}</p>
              </div>
            </div>
            <div className={getStatusColor(result.dmarc.status).split(' ')[0]}>
              {getStatusIcon(result.dmarc.status)}
            </div>
          </div>
          <div className="bg-zinc-50 p-3 rounded-xl mb-4 min-h-16 flex items-center">
            <p className="text-sm font-medium text-zinc-700">{result.dmarc.message}</p>
          </div>
          <div className="space-y-2">
            {result.dmarc.record ? (
              <div className="text-xs font-mono text-zinc-500 bg-zinc-100/50 p-2 rounded truncate" title={result.dmarc.record}>{result.dmarc.record}</div>
            ) : (
              <div className="text-xs text-zinc-400 italic">No record</div>
            )}
          </div>
        </div>

        {/* CAA */}
        <div className={`bg-white rounded-[2rem] p-6 border shadow-sm relative overflow-hidden transition-all hover:shadow-md ${getStatusColor(result.caa.status).replace('bg-', 'hover:bg-').replace('border-', 'hover:border-')}`}>
          <div className="flex items-center justify-between mb-4">
            <div className="flex items-center gap-3">
              <div className={`p-2 rounded-xl ${getStatusColor(result.caa.status)}`}>
                <Lock className="w-5 h-5" />
              </div>
              <div>
                <h4 className="font-bold text-zinc-900">{t.caaTitle}</h4>
                <p className="text-xs text-zinc-500">{t.caaDesc}</p>
              </div>
            </div>
            <div className={getStatusColor(result.caa.status).split(' ')[0]}>
              {getStatusIcon(result.caa.status)}
            </div>
          </div>
          <div className="bg-zinc-50 p-3 rounded-xl mb-4 min-h-16 flex items-center">
            <p className="text-sm font-medium text-zinc-700">{result.caa.message}</p>
          </div>
          <div className="space-y-2">
            {result.caa.records.map((r, i) => (
              <div key={i} className="text-xs font-mono text-zinc-500 bg-zinc-100/50 p-2 rounded truncate" title={r}>{r}</div>
            ))}
            {result.caa.records.length === 0 && <div className="text-xs text-zinc-400 italic">No record</div>}
          </div>
        </div>

      </div>
    </div>
  )
}
